data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/Shenzhen/war/GaussianSR/code/models/gaussian.py", line 298, in forward
    self.H = int(torch.round(inp.shape[-2]*scale[0]))
  File "/data/Shenzhen/war/GaussianSR/code/models/gaussian.py", line 256, in query_output
    # para_sum = torch.sum(para,dim = 0)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

                                                        
Traceback (most recent call last):
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 338, in <module>
    main(config, save_path, args)
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 245, in main
    train_loss = train(train_loader, model, optimizer)
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 201, in train
    loss.backward()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'DivBackward0' returned nan values in its 0th output.





/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/autograd/__init__.py:197: UserWarning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/Shenzhen/war/GaussianSR/code/models/gaussian.py", line 299, in forward
    self.W = int(torch.round(inp.shape[-1]*scale[0]))
  File "/data/Shenzhen/war/GaussianSR/code/models/gaussian.py", line 255, in query_output
    # para = torch.tanh(para)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at ../torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

                                                        
Traceback (most recent call last):
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 338, in <module>
    main(config, save_path, args)
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 245, in main
    train_loss = train(train_loader, model, optimizer)
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 201, in train
    loss.backward()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'DivBackward0' returned nan values in its 0th output.






Traceback (most recent call last):
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 338, in <module>
    main(config, save_path, args)
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 245, in main
    train_loss = train(train_loader, model, optimizer)
  File "/data/Shenzhen/war/GaussianSR/code/train_gaussian.py", line 126, in train
    for batch in tqdm(train_loader, leave=False, desc='train'):
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 128, in collate
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 128, in <dictcomp>
    return elem_type({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 120, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/data/Shenzhen/war/GaussianSR/env/env/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable
